# Generated by Django 5.0.2 on 2024-02-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_stock',
            field=models.FloatField(),
        ),
    ]
