# Generated by Django 5.0.2 on 2024-02-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree', '0002_alter_item_available_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.FloatField(),
        ),
    ]
