# Generated by Django 5.0.2 on 2024-02-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree', '0003_alter_item_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_status',
            field=models.CharField(default='In Stock', max_length=100),
        ),
    ]
